### ISSUE TITLE
Set rails environment to production?

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-samvera#17]
Is there any reason not to include RAILS_ENV=production in the environment instead of having to prefix every command with it?

**Comment by ksclarke** [comment]
Perhaps if you're also using the ansible roles to build a dev box? If you set it in the environment you'd need to reset that value to 'development' in a separate step for the dev box, whereas doing it in every command keeps the configuration specific to the installation. Not a big deal to reset that value for a dev box, but just mentioning it as one possible use case.

**Comment by bess** [comment]
It's not clear to me what this is talking about. We handle this just fine afaik.
