### ISSUE TITLE
Cache fits install package somewhere

### ISSUE THREAD

**Issue by bess** [curationexperts/ansible-samvera#34]
Today the fits download site went offline. I hope it comes back soon, and in the meantime I've been able to copy the .zip file from previously installed machines, but we should cache important installers somewhere for these kinds of outages.

**Comment by sanfordd** [comment]
@bess I was looking at this area, a local copy on a deploy machine is easy to script out for a range of users but makes it a pain with multiple people handling deployments. Would an S3 fetch be a reasonable assumption?

**Comment by bess** [comment]
This doesn't seem like a high priority to me. The problem has never re-occurred.
