### ISSUE TITLE
Add Default SSH session timeout

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/ansible-samvera#40]
**ISSUE**
For security purposes our servers should drop ssh sessions after a specified amount of inactivity.  We want to be resilient on poor network connections though.

**PROPOSED SETTINGS**
ClientAliveInterval 120
ClientAliveCountMax 5

In the proposed settings, the client would have to fail at five consecutive 2-minute checks (i.e. 10 minutes), but would remain alive if the system provides a successful response in any one of the tries.  In the original, the session dies immediately on a single check at 10 minutes with no retries.

This needs to go in `/etc/ssh/sshd_config`
See sample at https://github.com/curationexperts/ansible-hydra/blob/master/roles/system_setup/templates/ssh_config

**Comment by bess** [comment]
This is now the default for our ssh config.

I also changed the logic of this role so that we're keeping our entire sshd_config file in version control, which is generally a better practice.

**Comment by mark-dce** [comment]
I'm 50/50 about keeping entire config files in version control vs. making changes to individual settings.  I've seen us fly through upgrades in the past and miss important config changes because we install upgrades and then write our old config files over them.  

I generally like the idea of having the whole file in version control, but I wonder how we mitigate (or watch for) potentially missing new configuration settings as we roll out system upgrades.
