### ISSUE TITLE
Create solr.yml and blacklight.yml

### ISSUE THREAD

**Issue by bess** [curationexperts/ansible-samvera#8]
They should be configured with the name of the solr index we created:

deploy@mira-fc4:/opt/epigaea/current/config$ cat solr.yml
production:
  url: http://127.0.0.1:8983/solr/epigaea

deploy@mira-fc4:/opt/epigaea/current/config$ cat blacklight.yml
production:
  adapter: solr
  url: http://127.0.0.1:8983/solr/epigaea

**Comment by mark-dce** [comment]
I thought we decided to check these directly into the primary code repository instead of having Ansible manage them.  At least when we're running on a single server (against localhost / 127.0.0.1) there doesn't seem to be any secret or sensitive information here.

**Comment by bess** [comment]
Agree. Closing this ticket.
